name: Continuous Integration and Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          uv venv
          uv sync
      - name: Run test with Pytest
        run: |
          uv run pytest

  build-docker-image:
    runs-on: ubuntu-22.04
    needs: tests # Ensure tests pass before building the Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set in the repository (Settings > Secrets and variables > Actions)
          password: ${{ secrets.DOCKER_PASSWORD }} # Set in the repository (Settings > Secrets and variables > Actions)
      - name: Set Docker tag from latest Git tag
        id: get_tag
        run: |
          # Fetch all tags
          git fetch --tags
          # Get the latest tag (sorted by version)
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "IMAGE_TAG=$LATEST_TAG" >> $GITHUB_ENV
      - name: Set up Docker Buildx (ball detection)
        uses: docker/setup-buildx-action@v3
      - name: Build & Push Docker Image (ball detection)
        uses: docker/build-push-action@v6
        with:
          file: ./docker/ball_detection/Dockerfile
          platforms: linux/amd64 # Build for amd64 architecture only to avoid reaching time limits with GitHub Actions
          push: false # Set to true, to push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/football-game-tracking-ball-detection:${{ env.IMAGE_TAG }}
      - name: Set up Docker Buildx (player detection)
        uses: docker/setup-buildx-action@v3
      - name: Build & Push Docker Image (player detection)
        uses: docker/build-push-action@v6
        with:
          file: ./docker/player_detection/Dockerfile
          platforms: linux/amd64 # Build for amd64 architecture only to avoid reaching time limits with GitHub Actions
          push: false # Set to true, to push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/football-game-tracking-player-detection:${{ env.IMAGE_TAG }}
      - name: Set up Docker Buildx (pitch detection)
        uses: docker/setup-buildx-action@v3
      - name: Build & Push Docker Image (pitch detection)
        uses: docker/build-push-action@v6
        with:
          file: ./docker/pitch_detection/Dockerfile
          platforms: linux/amd64 # Build for amd64 architecture only to avoid reaching time limits with GitHub Actions
          push: false # Set to true, to push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/football-game-tracking-pitch-detection:${{ env.IMAGE_TAG }}
      - name: Set up Docker Buildx (ollama)
        uses: docker/setup-buildx-action@v3
      - name: Build & Push Docker Image (ollama)
        uses: docker/build-push-action@v6
        with:
          file: ./docker/ollama/Dockerfile
          platforms: linux/amd64 # Build for amd64 architecture only to avoid reaching time limits with GitHub Actions
          push: false # Set to true, to push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/football-game-tracking-ollama:${{ env.IMAGE_TAG }}
      - name: Set up Docker Buildx (full app)
        uses: docker/setup-buildx-action@v3
      - name: Build & Push Docker Image (full app)
        uses: docker/build-push-action@v6
        with:
          file: ./docker/full-app/Dockerfile
          platforms: linux/amd64 # Build for amd64 architecture only to avoid reaching time limits with GitHub Actions
          push: false # Set to true, to push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/football-game-tracking-app:${{ env.IMAGE_TAG }}


  # deploy:
  #   needs: build-docker-image
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Deploy to server
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_HOST }} # Set in the repository (Settings > Secrets and variables > Actions)
  #         username: ${{ secrets.SSH_USER }} # Set in the repository (Settings > Secrets and variables > Actions)
  #         key: ${{ secrets.SSH_PRIVATE_KEY }} # Set in the repository (Settings > Secrets and variables > Actions)
  #
  #         # Moves into the directory on your server that contains docker-compose.yml
  #         # Downloads the latest Docker images defined in docker-compose.yml on the server
  #         # Starts or updates containers
  #         # Deletes unused Docker images to free up space
  #         script: |
  #           cd /srv/football-game-tracking
  #           docker compose pull
  #           docker compose up -d
  #           docker image prune -f
